"""Added ambulance_name to ambulances

Revision ID: cbfe625511e3
Revises: db9929b9e92e
Create Date: 2025-02-04 16:30:57.223527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfe625511e3'
down_revision: Union[str, None] = 'db9929b9e92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ambulances', sa.Column('ambulance_name', sa.String(), nullable=False))
    op.alter_column('ambulances', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('available', 'unavailable', 'on_the_way', 'completed', name='statusenum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ambulances', 'status',
               existing_type=sa.Enum('available', 'unavailable', 'on_the_way', 'completed', name='statusenum'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    op.drop_column('ambulances', 'ambulance_name')
    # ### end Alembic commands ###
