"""Added status column to Ambulance

Revision ID: db9929b9e92e
Revises: 
Create Date: 2025-02-02 19:03:50.423174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9929b9e92e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ambulances', sa.Column('status', sa.Enum('available', 'occupied', name='statusenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ambulances', 'status')
    # ### end Alembic commands ###
